### ISSUE TITLE
[UST-245][Feature][Frontend] Optimize Report Form Text to Clarify Community-Based Judgment Process

### ISSUE THREAD

**Issue by UranusLin** [social-tw/social-tw-website#538] opened 2024-10-15 09:11 UTC
## Description

- 根據 [figma](https://www.figma.com/design/WFpSKfe9741XSlXkOXz8s0/Unirep-Social?node-id=3846-8258&node-type=canvas) 中「檢舉流程與文案內容優化」部分，當點擊檢舉時會先顯示檢舉說明在點擊進行檢舉後，畫面要新增`欲檢舉之內容`的顯示區塊

![image (9)](https://github.com/user-attachments/assets/397f8ba8-b0bd-44d2-8dd0-c4f21ff166c7)
![image (10)](https://github.com/user-attachments/assets/1b39f9f4-c0cd-43cb-a2af-3c1be19e9db5)

Story point: 1
Reporter: @UranusLin

**Comment by Xiawpohr** [comment] 2024-12-11 05:07
Closed this issue as it is a duplicate of #560 .

**Closed by Xiawpohr** 2024-12-11 05:07 UTC
Labels: feature, design, open to all
