### ISSUE TITLE
[relay] tests might fail randomly

### ISSUE THREAD

**Issue by vivianjeng** [social-tw/social-tw-website#119] opened 2023-09-29 05:42 UTC
**Describe the bug**
The same commitment, it fails at the first time
https://github.com/social-tw/social-tw-website/actions/runs/6346561855/attempts/1
but when I re-run the test, it succeeds
https://github.com/social-tw/social-tw-website/actions/runs/6346561855/attempts/2

**To Reproduce**
(not sure the reason)

**Expected behavior**
Succeeds all the time

**Screenshots**
<img width="750" alt="截圖 2023-09-29 上午11 37 06" src="https://github.com/social-tw/social-tw-website/assets/17507085/b1893f88-d990-49cd-9460-0a58e2973b5d">

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Lisooo790926** [comment] 2023-09-30 05:16
Hi @vivianjeng 
I might guess this issue is coming from `handleUserSignUp` in `UnirepSocialSynchronizer`
![image](https://github.com/social-tw/social-tw-website/assets/48560984/10a5fb10-a93e-4414-bf07-21bec7113576)
The `create` method from SQLiteConnector is return Promise 
I think after adding await, this issue should be fixed. 
#120

**Comment by Lisooo790926** [comment] 2023-10-06 13:37
After investigate, we found out the root cause is still the Synchronizer.
Since we create new [UnirepSocialSynchronizer](https://github.com/social-tw/social-tw-website/blob/e083f3080c2652687faa95286e3ecee329d8d00f/packages/relay/src/index.ts#L42) and start to listen our new events, but our [userState](https://github.com/social-tw/social-tw-website/blob/e083f3080c2652687faa95286e3ecee329d8d00f/packages/frontend/src/contexts/User.tsx#L134) uses [the old Synchronizer](https://github.com/Unirep/Unirep/blob/b51a3a4363d3df2aca4c390849aeed3bb0d4ee47/packages/core/src/UserState.ts#L89) instead of UnirepSocialSynchronizer, so even call waitForSync, our new events will not be listened.

Also we found the args [db](https://github.com/Unirep/Unirep/blob/b51a3a4363d3df2aca4c390849aeed3bb0d4ee47/packages/core/src/Synchronizer.ts#L540) in handleEvent method is type of TransactionDB, it's not Promise method, so we could remove the await.

In sum, will use UnirepSocialSynchronizer to fix this issue

**Closed by Lisooo790926** 2023-10-06 13:37 UTC
Labels: bug, test, relayer
