### ISSUE TITLE
[UST-71][Frontend] Refactor useUser ans userState 

### ISSUE THREAD

**Issue by UranusLin** [social-tw/social-tw-website#305] opened 2024-04-26 04:37 UTC
**Is your feature request related to a problem? Please describe.**
I'm encountering an issue where the userState retrieved from useUser() hook is undefined at the initial render of some pages. This leads to problems as the subsequent code expects a valid UserState object, causing runtime errors when attempting to access properties or methods on undefined.

**Describe the solution you'd like**
I propose enhancing the initialization and consumption of userState within the UserProvider. This involves:

Initializing userState with Async Loading: Implement an async initialization pattern inside the UserProvider. This ensures that userState is fully prepared before any components relying on it are rendered. Use a loading state (isLoading) to manage and block the rendering process until the userState is fully loaded.
Robust Error Handling and Loading Indicators: During the userState initialization phase, any errors should be caught, and appropriate fallback or error states should be displayed. Additionally, provide a loading indicator to inform the user that the application state is being prepared.
Dependent Component Adjustments: Adjust all components that depend on userState to react appropriately to the loading and error states, preventing them from executing logic that depends on a fully initialized userState.

**Comment by Xiawpohr** [comment] 2024-05-16 14:13
close this issue because it is a duplicate of #352

**Closed by Xiawpohr** 2024-05-16 14:13 UTC
Labels: feature
